use anyhow::Result;
use log::{debug, error};
use redis::AsyncCommands;
use std::sync::Arc;
use tokio::sync::Mutex;

/// Redis Streams XADD wrapper (ADR-0015).
///
/// Used by CandleStreamer to publish closed candle events to
/// `stream:candles:{interval}` for consumption by the API alert engine.
///
/// Key difference from Broadcaster (Pub/Sub):
/// - Pub/Sub: fire-and-forget, no persistence → used for ticks
/// - Streams: persistent log with consumer groups → used for OHLCV candles
pub struct RedisStream {
    connection: Arc<Mutex<redis::aio::MultiplexedConnection>>,
    /// Maximum number of entries retained per stream key (MAXLEN ~)
    max_len: usize,
}

impl RedisStream {
    pub async fn new(redis_url: &str) -> Result<Self> {
        let client = redis::Client::open(redis_url)?;
        let conn = client.get_multiplexed_tokio_connection().await?;
        Ok(Self {
            connection: Arc::new(Mutex::new(conn)),
            max_len: 50_000, // ~34 days of 1m candles for 1 symbol
        })
    }

    /// XADD a closed candle to `stream:candles:{interval}`.
    ///
    /// Entry ID is auto-generated by Redis (`*`).
    /// Fields match the schema defined in ADR-0015.
    pub async fn publish_candle(
        &self,
        symbol: &str,
        interval: &str,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
        timestamp: i64, // unix seconds UTC (bar close time)
    ) -> Result<()> {
        let stream_key = format!("stream:candles:{}", interval);

        let fields: &[(&str, &str)] = &[
            ("symbol", symbol),
            ("interval", interval),
            ("open", &open.to_string()),
            ("high", &high.to_string()),
            ("low", &low.to_string()),
            ("close", &close.to_string()),
            ("volume", &volume.to_string()),
            ("timestamp", &timestamp.to_string()),
        ];

        let mut conn = self.connection.lock().await;

        // XADD with MAXLEN ~ (approximate trimming for performance)
        let result: Result<String, redis::RedisError> = redis::cmd("XADD")
            .arg(&stream_key)
            .arg("MAXLEN")
            .arg("~")
            .arg(self.max_len)
            .arg("*") // auto ID
            .arg(
                fields
                    .iter()
                    .flat_map(|(k, v)| [*k, *v])
                    .collect::<Vec<_>>()
                    .as_slice(),
            )
            .query_async(&mut *conn)
            .await;

        match result {
            Ok(id) => {
                debug!(
                    "✅ XADD {}/{} → {} (id={})",
                    symbol, interval, stream_key, id
                );
                Ok(())
            }
            Err(e) => {
                error!("❌ XADD failed for {}/{}: {}", symbol, interval, e);
                Err(e.into())
            }
        }
    }

    /// Ensure consumer group exists for a stream key.
    /// Call this from the API side (CandleConsumer) on startup.
    pub async fn ensure_consumer_group(&self, stream_key: &str, group_name: &str) -> Result<()> {
        let mut conn = self.connection.lock().await;
        let result: Result<(), redis::RedisError> = redis::cmd("XGROUP")
            .arg("CREATE")
            .arg(stream_key)
            .arg(group_name)
            .arg("$") // only new messages from now
            .arg("MKSTREAM") // create stream if not exists
            .query_async(&mut *conn)
            .await;

        match result {
            Ok(_) => {
                debug!(
                    "Consumer group '{}' created for '{}'",
                    group_name, stream_key
                );
                Ok(())
            }
            Err(e) if e.to_string().contains("BUSYGROUP") => {
                // Already exists — idempotent
                debug!(
                    "Consumer group '{}' already exists for '{}'",
                    group_name, stream_key
                );
                Ok(())
            }
            Err(e) => Err(e.into()),
        }
    }

    /// Check if backfill is paused by API (ADR-0021)
    pub async fn is_backfill_paused(&self) -> bool {
        let mut conn = self.connection.lock().await;
        let result: Option<String> = redis::cmd("GET")
            .arg("harvest:backfill:paused")
            .query_async(&mut *conn)
            .await
            .unwrap_or_default();

        result.is_some()
    }
}
