FROM oven/bun:1.2-slim

WORKDIR /app
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv && \
    pip3 install --break-system-packages pandas tradingview-scraper --no-cache-dir


# Copy root package.json and lockfile
COPY package.json bun.lock ./
# Copy workspaces package.json
COPY apps/api/package.json ./apps/api/
COPY packages/db/package.json ./packages/db/
COPY packages/analysis/package.json ./packages/analysis/
COPY packages/shared/package.json ./packages/shared/

# Skip bun install in image since we rely on host bind mount in dev
# RUN bun install

# Copy source
COPY apps/api ./apps/api
COPY packages/db ./packages/db
COPY packages/analysis ./packages/analysis
COPY packages/shared ./packages/shared

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["bun", "run", "dev"]
